//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorSchema
    {
        public int Id { get; set; }
        public string colorOne { get; set; }
        public string colorTwo { get; set; }
        public string colorThree { get; set; }
        public string colorFive { get; set; }
        public string colorFour { get; set; }
    }
}
