//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FAQ> FAQSet { get; set; }
        public virtual DbSet<Checklist> ChecklistSet { get; set; }
        public virtual DbSet<ApplicationProcedure> ApplicationProcedureSet { get; set; }
        public virtual DbSet<University> UniversitySet { get; set; }
        public virtual DbSet<FirstSteps> FirstStepsSet { get; set; }
        public virtual DbSet<ColorSchema> ColorSchemaSet { get; set; }
        public virtual DbSet<Calendar> CalendarSet { get; set; }
        public virtual DbSet<Housing> HousingSet { get; set; }
        public virtual DbSet<Departments> DepartmentsSet { get; set; }
        public virtual DbSet<POI> POISet { get; set; }
    }
}
